// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MigrationService is an autogenerated mock type for the MigrationService type
type MigrationService struct {
	mock.Mock
}

// Migrate provides a mock function with given fields: ctx
func (_m *MigrationService) Migrate(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMigrationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewMigrationService creates a new instance of MigrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMigrationService(t mockConstructorTestingTNewMigrationService) *MigrationService {
	mock := &MigrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
