// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionHandleFunc is an autogenerated mock type for the TransactionHandleFunc type
type TransactionHandleFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *TransactionHandleFunc) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionHandleFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionHandleFunc creates a new instance of TransactionHandleFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionHandleFunc(t mockConstructorTestingTNewTransactionHandleFunc) *TransactionHandleFunc {
	mock := &TransactionHandleFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
