// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aydinmuzaffer/migration-tool-service/src/migrationtool/domain"
	mock "github.com/stretchr/testify/mock"
)

// VenderDeliveryAreaSetter is an autogenerated mock type for the VenderDeliveryAreaSetter type
type VenderDeliveryAreaSetter struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, areas
func (_m *VenderDeliveryAreaSetter) Insert(ctx context.Context, areas *[]domain.VendorDeliveryAreaModel) error {
	ret := _m.Called(ctx, areas)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]domain.VendorDeliveryAreaModel) error); ok {
		r0 = rf(ctx, areas)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewVenderDeliveryAreaSetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewVenderDeliveryAreaSetter creates a new instance of VenderDeliveryAreaSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVenderDeliveryAreaSetter(t mockConstructorTestingTNewVenderDeliveryAreaSetter) *VenderDeliveryAreaSetter {
	mock := &VenderDeliveryAreaSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
