// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aydinmuzaffer/migration-tool-service/src/migrationtool/domain"
	mock "github.com/stretchr/testify/mock"
)

// VenderDeliveryAreaPolygonGetter is an autogenerated mock type for the VenderDeliveryAreaPolygonGetter type
type VenderDeliveryAreaPolygonGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, ids
func (_m *VenderDeliveryAreaPolygonGetter) Get(ctx context.Context, ids *[]int64) ([]domain.VendorDeliveryAreaPolygonGetModel, error) {
	ret := _m.Called(ctx, ids)

	var r0 []domain.VendorDeliveryAreaPolygonGetModel
	if rf, ok := ret.Get(0).(func(context.Context, *[]int64) []domain.VendorDeliveryAreaPolygonGetModel); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.VendorDeliveryAreaPolygonGetModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *[]int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewVenderDeliveryAreaPolygonGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewVenderDeliveryAreaPolygonGetter creates a new instance of VenderDeliveryAreaPolygonGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVenderDeliveryAreaPolygonGetter(t mockConstructorTestingTNewVenderDeliveryAreaPolygonGetter) *VenderDeliveryAreaPolygonGetter {
	mock := &VenderDeliveryAreaPolygonGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
